## Inputs and Outputs

In [1]:
sum([10, 20, 30])

60

In [2]:
lst = [10, 20, 30]
sum(lst)

60

In [3]:
lst[0]

10

In [4]:
len(lst)

3

In [5]:
listlen = len(lst)
listlen

3

In [6]:
# Exercise
# Compute the average of the variable lst
avg = sum(lst)/len(lst)
print(avg)

20.0


## Python Libraries (Numpy)

In [7]:
# Import functions from modules (in this case numpy)
import numpy as np

In [8]:
np.mean(lst)

20.0

In [9]:
# linearly spaced number (sequence in R)
np.linspace(1, 8, 20)

array([1.        , 1.36842105, 1.73684211, 2.10526316, 2.47368421,
       2.84210526, 3.21052632, 3.57894737, 3.94736842, 4.31578947,
       4.68421053, 5.05263158, 5.42105263, 5.78947368, 6.15789474,
       6.52631579, 6.89473684, 7.26315789, 7.63157895, 8.        ])

In [10]:
np.linspace(1, 80, 20)

array([ 1.        ,  5.15789474,  9.31578947, 13.47368421, 17.63157895,
       21.78947368, 25.94736842, 30.10526316, 34.26315789, 38.42105263,
       42.57894737, 46.73684211, 50.89473684, 55.05263158, 59.21052632,
       63.36842105, 67.52631579, 71.68421053, 75.84210526, 80.        ])

In [11]:
number = [1,2,3,4,5,6]
type(number)

list

In [12]:
numbernp = np.array(number)
type(numbernp)

numpy.ndarray

In [13]:
print(number)
print()
print(numbernp)

[1, 2, 3, 4, 5, 6]

[1 2 3 4 5 6]


In [14]:
numbernp.min()

1

In [15]:
numbernp.max()

6

In [16]:
np.min(numbernp)

1

In [17]:
np.max(numbernp)

6

In [18]:
n = [4,6,7,3,4,7,7,9]
print(n)
n.sort()
print(n)

[4, 6, 7, 3, 4, 7, 7, 9]
[3, 4, 4, 6, 7, 7, 7, 9]


In [19]:
print(type(n))
n = np.sort(n)
print(type(n))

<class 'list'>
<class 'numpy.ndarray'>


In [20]:
n = list(np.sort(n))
print(type(n))

<class 'list'>


## Python Libraries (Pandas)

In [21]:
# Pamdas stores data in table format which is easy to store, see and manipulate
import pandas as pd

In [22]:
# Les create some random number data
var1 = np.random.randn(100)*5 + 20
var1

array([14.71971142, 16.92583276, 19.45493236, 15.00186581, 20.82448164,
       25.05762655, 28.51457277, 22.88538558, 22.48135281, 19.33858469,
       17.93784411, 31.37379235, 21.71020926, 17.48923102, 18.34943412,
       22.32208047, 23.05231569, 19.05227762, 22.99073115, 22.1067945 ,
       26.45927741, 31.44231462, 13.55194974, 21.67489895, 20.14966387,
       24.12978296, 14.37924646, 13.34809152, 18.27954692, 11.67031612,
       16.47312648, 12.74660023, 21.15158163, 18.89039664, 13.79884131,
       23.47502329, 18.22238127, 23.20058606, 23.76618965, 17.45968942,
        8.44859299, 23.64709279, 22.78735159, 24.50036989, 28.85624314,
       23.21579496, 24.54821251,  9.55793314, 13.91309223, 24.65867941,
       25.03658171, 18.65661617, 23.50182611, 21.69583246, 20.04083767,
       17.01081576,  9.06296248, 15.56600147, 19.8968513 , 12.72537899,
       15.48882141, 26.28106862, 12.95073002, 15.25199549, 18.01071324,
       17.79058262, 19.96348687,  7.25444858, 16.33533008, 16.96

In [23]:
np.mean(var1)

19.239896011194386

In [24]:
var2 = np.random.randn(100) > 0
var2

array([ True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True, False, False,  True, False, False,  True,  True,
        True, False, False,  True,  True, False, False,  True,  True,
       False,  True,  True, False, False,  True,  True, False,  True,
       False,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True, False,
        True, False,  True, False,  True,  True,  True,  True, False,
       False,  True,  True,  True, False, False, False, False,  True,
        True,  True,  True, False, False, False, False, False, False,
        True,  True,  True, False,  True, False, False,  True,  True,
        True])

In [25]:
np.mean(var2)

0.63

In [26]:
labels = ["Temp. (C)", "Ice cream eaten"]

In [27]:
# Create a dictionary contianing this dataset
d = {labels[0]:var1, labels[1]:var2}
d

{'Temp. (C)': array([14.71971142, 16.92583276, 19.45493236, 15.00186581, 20.82448164,
        25.05762655, 28.51457277, 22.88538558, 22.48135281, 19.33858469,
        17.93784411, 31.37379235, 21.71020926, 17.48923102, 18.34943412,
        22.32208047, 23.05231569, 19.05227762, 22.99073115, 22.1067945 ,
        26.45927741, 31.44231462, 13.55194974, 21.67489895, 20.14966387,
        24.12978296, 14.37924646, 13.34809152, 18.27954692, 11.67031612,
        16.47312648, 12.74660023, 21.15158163, 18.89039664, 13.79884131,
        23.47502329, 18.22238127, 23.20058606, 23.76618965, 17.45968942,
         8.44859299, 23.64709279, 22.78735159, 24.50036989, 28.85624314,
        23.21579496, 24.54821251,  9.55793314, 13.91309223, 24.65867941,
        25.03658171, 18.65661617, 23.50182611, 21.69583246, 20.04083767,
        17.01081576,  9.06296248, 15.56600147, 19.8968513 , 12.72537899,
        15.48882141, 26.28106862, 12.95073002, 15.25199549, 18.01071324,
        17.79058262, 19.96348687,  7.2

In [28]:
df = pd.DataFrame(data = d)
df.head()

Temp. (C)  Ice cream eaten
0  14.719711             True
1  16.925833             True
2  19.454932             True
3  15.001866             True
4  20.824482             True

In [29]:
df.tail()

Temp. (C)  Ice cream eaten
95  16.572513            False
96   9.687023            False
97  21.581009             True
98  17.074158             True
99  19.911453             True

In [30]:
df.count()

Temp. (C)          100
Ice cream eaten    100
dtype: int64

In [31]:
# Average value of each column
df.mean()

Temp. (C)          19.239896
Ice cream eaten     0.630000
dtype: float64

In [32]:
# Exercise
# Create a Pandas fd wth three variables
# 1) integers 0 to 10
# 2) their square
# 3) their log
ints = np.random.randint(0, 10, 100)
int_sq = ints**2
int_log = np.log(ints)
d = {"integers":ints, "integers square":int_sq, "log integers": int_log}
df = pd.DataFrame(data = d)
df.head()

/var/folders/wh/83kd80754n51v2m2g0jx2wynk10f9n/T/ipykernel_4925/3664092326.py:8: RuntimeWarning: divide by zero encountered in log
  int_log = np.log(ints)


integers  integers square  log integers
0         2                4      0.693147
1         2                4      0.693147
2         6               36      1.791759
3         1                1      0.000000
4         1                1      0.000000

In [33]:
# Another version
nums = np.array(range(11))
D = {"integers":nums, "square": nums**2, "log": np.log(nums)}
df = pd.DataFrame(data = D)
df

/var/folders/wh/83kd80754n51v2m2g0jx2wynk10f9n/T/ipykernel_4925/1217252105.py:3: RuntimeWarning: divide by zero encountered in log
  D = {"integers":nums, "square": nums**2, "log": np.log(nums)}


integers  square       log
0          0       0      -inf
1          1       1  0.000000
2          2       4  0.693147
3          3       9  1.098612
4          4      16  1.386294
5          5      25  1.609438
6          6      36  1.791759
7          7      49  1.945910
8          8      64  2.079442
9          9      81  2.197225
10        10     100  2.302585

## Getting Help on Functions

In [34]:
alist = [1, 2, 3]
sum(alist)

6

In [35]:
sum(alist, 1)

7

In [36]:
sum(alist,10)

16

In [37]:
sum(alist, -6)

0

In [38]:
sum??

In [39]:
help(sum)

Help on built-in function sum in module builtins:

sum(iterable, /, start=0)
    Return the sum of a 'start' value (default: 0) plus an iterable of numbers
    
    When the iterable is empty, return the start value.
    This function is intended specifically for use with numeric values and may
    reject non-numeric types.



In [40]:
import inspect

In [41]:
# Read the source files
# inspect.getsourcelines(np.linspace)

## Creating Functions

In [42]:
# How to crete functions from scratch
def awesomeFunction():
    print(1+1)
awesomeFunction()

2


In [43]:
awesomeFunction

<function __main__.awesomeFunction()>

In [44]:
def superAwesomeFunction(input1, input2):
    return input1 + input2
superAwesomeFunction(5, 5)

10

In [45]:
# No output because there is no return command in function
# The function doesnt return anything
output = awesomeFunction()
print(output)

2
None


In [46]:
output = superAwesomeFunction(5, 5)
print(output)

10


In [47]:
def funfun(in1, in2):
    sumres = in1 + in2
    prodres = in1*in2
    print("Their sum is", sumres)
    print("Their product is", prodres)
    return sumres, prodres

funfun(3,4)

Their sum is 7
Their product is 12


(7, 12)

In [48]:
out = funfun(3,4)
print(out[0])
print(out[1])

Their sum is 7
Their product is 12
7
12


In [49]:
outS, outP = funfun(3,4)
print(outS, outP)

Their sum is 7
Their product is 12
7 12


In [50]:
# lambda functions: often used in mathemaics, one-line function
# you cannot continue to the next line with lambda, they are convenient for short things only
littlefun = lambda x : x**2 - 1
littlefun(4)

15

In [51]:
# Exercise
# Create a function that computes the factorial of an integer
# 5! = 5*4*3*2*1
# compare the output of this function against the factorial function of math module
import math
def fct(x):
    a = list(range(1,x+1))
    return np.product(a)
fct(5)

120

In [52]:
math.factorial(5)

120

In [53]:
# another verson with numpy
val = 4
np.arange(1,val+1)
np.product(np.arange(1, val+1))

24

In [54]:
fct(23)

8128291617894825984

## Global and Local Variable Scopes

In [55]:
# Local scope (variables do not exist in the global environment)
# variable accessed only inside the function
def funfun():
    x = 7
    y = 10
    print(x)
funfun()

7


In [56]:
x = 3
funfun()
print(x)
# print(y)

7
3


In [57]:
# Global scope: variable created outside the function
z = 2
def fz():
    print(z)
fz()

2


In [58]:
# Exercise
# Write a function that flips a coin n-times and reports the average
N = 100000
def flip(N):
    return np.mean(np.random.randint(0,2,N))
flip(N)

0.49744

In [59]:
def coinflip(N):
    return np.mean(np.random.randn(N)>0)
coinflip(N)

0.50016

## Classes and Object-Oriented Programming (OOP)

In [60]:
# Class is like a dictionary because it can store various 
# pieces of information
class Experiment(object):
    # constructor method
    def __init__(self, eType, dataN, status = "ongoing"):
        self.expType = eType
        self.dataCount = dataN
        self.expStatus = status
        
    def increaseN(self, number):
        self.dataCount += number
        
    def changeExpStatus(self, status):
        self.expStatus = status
        
    def __str__(self):
        return "Experiment type: " + self.expType + " has " + str(self.dataCount) + " data points. "

In [61]:
myexperiment = Experiment("Brain", 120)
myexperiment

In [62]:
print(myexperiment.dataCount)

120


In [63]:
myexperiment = Experiment("Brain", 140)
print(myexperiment.dataCount)
myexperiment.increaseN(1450)
print(myexperiment.dataCount)
print(myexperiment)

140
1590
Experiment type: Brain has 1590 data points. 


In [64]:
# Exercise
# Create a class to store information about your board game hobby.
# The class must contain ifnormation about:
# 1 - Name of the board game
# 2 - Number of times yo have plaid
# 3 - Number of times you have won
# And the following methods
# 1 - Update N plays and N wins
# 2 - Print out the outcome of ther last game (win/lose)
# Create at least two different instances to make sure it works
class Boardgames(object):
    # constructor method
    def __init__(self, name, play, status):
        self.name = name
        self.play = play
        self.status = status
        
    def update(self, number, status):
        self.play += number
        self.status = status
        
    def __str__(self):
        return '{} {} {}'.format(self.name, self.play, self.status)

In [65]:
game = Boardgames("chess", 1, "win")
print(game)

chess 1 win


In [66]:
game.update(3, "lose")
print(game)

chess 4 lose
